### ISSUE TITLE
Fine-tuning for Android udev rule collection

### ISSUE THREAD

**Issue by elfring** [snowdream/51-android#7]
[The provided udev rule file](https://github.com/snowdream/51-android/blob/96c5f0f7167a73f6926f992f2ecfc5fd6a0331fd/51-android.rules#L1 "Update candidate") is using filter conditions which are too broad and therefore imprecise.
This specification approach can result in [some system configuration difficulties](https://bugzilla.suse.com/show_bug.cgi?id=938659#c52 "Clarification for the determination of appropriate device access permissions") if additional software application requirements will be considered.
How would you like to improve the affected rule collection?

**Comment by UncleDan** [comment]
Hi there. I am not compiling anymore, since I settled on a slightly modded
Sony stock firmware.
Il 01/ago/2015 06:50, "Markus Elfring" <notifications@github.com> ha
scritto:

**Comment by elfring** [comment]
Thanks for your feedback.

I hope that it will be possible to reduce system configuration difficulties around such a questionable rule collection version which might be still flying around the internet for a while.
